//
// 这是一个生成的文件，请勿编辑~ 编辑了也没用~  
// 请编辑同目录下其他 .ini 文件
// Generated by PilotCLI, see https://github.com/Rdxer/PilotCLI

import Foundation

// MARK: - 启动模式 {{ lauchModeFileName }} 
extension Env{

    /// Section => ["DEFAULT"] ⬇️{% for kv in DEFAULT %}
    public static let {{ kv.k }} = {{ kv.v }}{% endfor %}
    /// Section => ["DEFAULT"] ️⬆️
    
    {% for sec in otherSection %}
    /// Section => ["{{ sec.name }}"] ⬇️
    public struct {{ sec.name }}{
        {% for kvsec in sec.kvList %}
        public static let {{ kvsec.k }} = {{ kvsec.v }}{% endfor %}
        
    }   
    /// Section => ["{{ sec.name }}"] ⬆️
    {% endfor %}
    
    
}
